dev-3: Компонент кнопка
frontend-park-mail-ru/2024_2_42 pull request #1
Opened 2024-09-28 20:36 UTC by ironyyyr

Кнопка должна быть реализована как отдельный компонент и иметь следующие свойства

Умеет принимать функцию колбэк на нажатие

Имеет следующие стейты:

default

hover

active/press

disabled

Можно добавить иконку слева/справа

Должна уметь принимать svg для иконки

Имеет различные отображения:

primary

secondary

link

Написан JSDoc с описанием вышеперечисленного

2024-09-28 20:36 UTC, ironyyyr commented
Понимаю, что очень многое здесь может быть сделано неправильно
Готов к критике

2024-09-29 10:07 UTC, Gallaann requested changes
Не могу пока аппрув поставить, нужно фиксить

2024-09-29 10:07 UTC, Gallaann commented on source/components/input/input.css
> +  }
Как будто мало стилей для инпута. Просто к сведению, понимаю, что не твоя задача, но лучше чужие изменения не тащить в ПР, смотреть неудобно)

2024-09-29 10:07 UTC, Gallaann commented on source/components/input/input.hbs
> +</div>
Перевод строки, передай Вова

2024-09-29 10:07 UTC, Gallaann commented on source/index.html
> +</html>
И тут

2024-09-29 10:07 UTC, Gallaann commented on source/components/input/input.js
> +    }}
И тут

2024-09-29 10:07 UTC, Gallaann commented on source/index.js
> +// input.renderTemplate();
Перевод строки, а комменты лучше ударить

2024-09-29 10:07 UTC, Gallaann commented on source/module/validation.js
> +};
Перевод строки

2024-09-29 10:07 UTC, Gallaann commented on source/module/validation.js
> +export const validateInput = (input, rules) => {
JSDoc хочу видеть

2024-09-29 10:07 UTC, Gallaann commented on source/module/validation.js
> +const NICKNAMEPATTERN = /^[0-9a-zA-Z_]{3,20}$/;
Константы пишутся в upper snake case, например, `EMAIL_PATTERN`

2024-09-29 10:07 UTC, Gallaann commented on source/module/validation.js
> +        }
Неудачные ошибки, пользователю будет неудобно искать какие он там символы не ввел или ввел лишние, особенно, если инпут будет закрыт звездочками

2024-09-29 10:07 UTC, Gallaann commented on source/components/button/button.css
> +  background-color: #007bff;
Вынести в общий файл для css vars, чтобы былло понятно что за цвет и не приходилось думать куда и что написали и заюзали. Все что ниже - аналогично

2024-09-29 10:07 UTC, Gallaann commented on source/components/button/button.css
> +  font-family: Arial, sans-serif;
По-хорошему для текстов тоже нужно создать отдельный css файлик, в котором будут классы по типу `.headline__primary` и такого типа. Вот в нем уже указать какая лигатура, высота линии и все, то относится конкретно к тексту, а потом этот класс навесить на компонент

2024-09-29 12:34 UTC, oruchim1001 commented on source/module/validation.js
> +const NICKNAMEPATTERN = /^[0-9a-zA-Z_]{3,20}$/;
я исправил в своей ветке https://github.com/frontend-park-mail-ru/2024_2_42/pull/2

2024-09-29 12:35 UTC, oruchim1001 commented on source/module/validation.js
> +export const validateInput = (input, rules) => {
https://github.com/frontend-park-mail-ru/2024_2_42/pull/2 - добавил у себя

2024-09-29 12:40 UTC, oruchim1001 commented on source/module/validation.js
> +        }
https://github.com/frontend-park-mail-ru/2024_2_42/pull/2 - поправил

2024-09-29 19:28 UTC, Gallaann approved these changes
Ок, поправь слегка

2024-09-29 19:28 UTC, Gallaann commented on source/components/button/button.css
> +}
А зачем тут селектор по элементу?

2024-09-29 19:28 UTC, Gallaann commented on README.md
Точно будет конфликт, там уже вмержили другой ридми, порешай его

2024-09-29 19:44 UTC, merged